### ISSUE TITLE
Just a question - hide the icons

### ISSUE THREAD

**Issue by NicosNicolaou16** [byanko55/jekyll-professional-resume#11]
Can I hide the social icon, for example the phone icon?

**Comment by byanko55** [comment]
> Can I hide the social icon, for example the phone icon?

It's quite simple: 

In `_config.yml`, just leave the corresponding field as blank.

![image](https://github.com/byanko55/jekyll-professional-resume/assets/132314568/eaabf57c-2125-4c4b-82ff-97b208617ed5)

**Comment by NicosNicolaou16** [comment]
Thank you very much
