### ISSUE TITLE
CSS is not rendering 

### ISSUE THREAD

**Issue by ethic-bakeery** [byanko55/jekyll-professional-resume#6]
I forked the report and enable GitHub pages when I visit GitHub link page the CSS is not loading 
![IMG-20240422-WA0004](https://github.com/byanko55/jekyll-professional-resume/assets/98848465/9287258b-d6ff-4256-8da6-02514ec2d676)

**Comment by byanko55** [comment]
I just fixed the related issue in #7.

Now, you need to do followings:
1. Merge changes into your repo.
2. Open `_config.yml`, and set the value of field `baseurl` as your repo name. (ex., */resume*)

**Comment by ethic-bakeery** [comment]
It worked, Thanks alot
